services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin1234
      - DB_NAME=taller1
    depends_on:
      - postgres
    networks:
      - internal_net

  frontend:
    build:
      context: ./frontend/notes-web-react
      dockerfile: Dockerfile
    container_name: react-web
    expose:
      - "5173"
    depends_on:
      - api
    networks:
      - internal_net
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: notes_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

volumes:
  postgres_data: